[2024-05-27 09:33:17,830] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.save_into_db 2024-05-27T09:33:09.855017+00:00 [queued]>
[2024-05-27 09:33:17,837] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.save_into_db 2024-05-27T09:33:09.855017+00:00 [queued]>
[2024-05-27 09:33:17,837] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-05-27 09:33:17,837] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-05-27 09:33:17,838] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-05-27 09:33:17,846] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): save_into_db> on 2024-05-27T09:33:09.855017+00:00
[2024-05-27 09:33:17,849] {standard_task_runner.py:52} INFO - Started process 186 to run task
[2024-05-27 09:33:17,852] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'load_init_data', 'save_into_db', '2024-05-27T09:33:09.855017+00:00', '--job-id', '479', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/load_init_data.py', '--cfg-path', '/tmp/tmpehja2fnz', '--error-file', '/tmp/tmph_1g75z5']
[2024-05-27 09:33:17,854] {standard_task_runner.py:77} INFO - Job 479: Subtask save_into_db
[2024-05-27 09:33:17,878] {logging_mixin.py:104} INFO - Running <TaskInstance: load_init_data.save_into_db 2024-05-27T09:33:09.855017+00:00 [running]> on host 1f334d963743
[2024-05-27 09:33:17,904] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_init_data
AIRFLOW_CTX_TASK_ID=save_into_db
AIRFLOW_CTX_EXECUTION_DATE=2024-05-27T09:33:09.855017+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-27T09:33:09.855017+00:00
[2024-05-27 09:33:18,115] {python.py:118} INFO - Done. Returned value was: None
[2024-05-27 09:33:18,123] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=load_init_data, task_id=save_into_db, execution_date=20240527T093309, start_date=20240527T093317, end_date=20240527T093318
[2024-05-27 09:33:18,140] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-27 09:33:18,160] {local_task_job.py:146} INFO - Task exited with return code 0
