[2024-05-26 21:55:02,590] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: get_new_data.transform 2024-05-26T21:52:23.478777+00:00 [queued]>
[2024-05-26 21:55:02,600] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: get_new_data.transform 2024-05-26T21:52:23.478777+00:00 [queued]>
[2024-05-26 21:55:02,600] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 21:55:02,601] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-05-26 21:55:02,601] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 21:55:02,607] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): transform> on 2024-05-26T21:52:23.478777+00:00
[2024-05-26 21:55:02,610] {standard_task_runner.py:52} INFO - Started process 293 to run task
[2024-05-26 21:55:02,613] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'get_new_data', 'transform', '2024-05-26T21:52:23.478777+00:00', '--job-id', '428', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/get_new_data.py', '--cfg-path', '/tmp/tmpx8trcpkr', '--error-file', '/tmp/tmptr6g1jww']
[2024-05-26 21:55:02,615] {standard_task_runner.py:77} INFO - Job 428: Subtask transform
[2024-05-26 21:55:02,641] {logging_mixin.py:104} INFO - Running <TaskInstance: get_new_data.transform 2024-05-26T21:52:23.478777+00:00 [running]> on host 9c777ac19e23
[2024-05-26 21:55:02,667] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_new_data
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2024-05-26T21:52:23.478777+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-26T21:52:23.478777+00:00
[2024-05-26 21:55:03,532] {python.py:118} INFO - Done. Returned value was: None
[2024-05-26 21:55:03,538] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=get_new_data, task_id=transform, execution_date=20240526T215223, start_date=20240526T215502, end_date=20240526T215503
[2024-05-26 21:55:03,555] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-26 21:55:03,573] {local_task_job.py:146} INFO - Task exited with return code 0
