[2024-06-09 14:02:29,062] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.save_into_db 2024-05-31T02:00:00+00:00 [queued]>
[2024-06-09 14:02:29,109] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.save_into_db 2024-05-31T02:00:00+00:00 [queued]>
[2024-06-09 14:02:29,116] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-06-09 14:02:29,124] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-06-09 14:02:29,138] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-06-09 14:02:29,257] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): save_into_db> on 2024-05-31T02:00:00+00:00
[2024-06-09 14:02:29,279] {standard_task_runner.py:52} INFO - Started process 270 to run task
[2024-06-09 14:02:29,322] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'load_init_data', 'save_into_db', '2024-05-31T02:00:00+00:00', '--job-id', '43', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/load_init_data.py', '--cfg-path', '/tmp/tmpg5v4j_7v', '--error-file', '/tmp/tmpisu8x_za']
[2024-06-09 14:02:29,357] {standard_task_runner.py:77} INFO - Job 43: Subtask save_into_db
[2024-06-09 14:02:29,482] {logging_mixin.py:104} INFO - Running <TaskInstance: load_init_data.save_into_db 2024-05-31T02:00:00+00:00 [running]> on host 97b873bf6d4d
[2024-06-09 14:02:29,583] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_init_data
AIRFLOW_CTX_TASK_ID=save_into_db
AIRFLOW_CTX_EXECUTION_DATE=2024-05-31T02:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-31T02:00:00+00:00
[2024-06-09 14:02:31,260] {python.py:118} INFO - Done. Returned value was: None
[2024-06-09 14:02:31,369] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=load_init_data, task_id=save_into_db, execution_date=20240531T020000, start_date=20240609T140229, end_date=20240609T140231
[2024-06-09 14:02:31,479] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-09 14:02:31,530] {local_task_job.py:146} INFO - Task exited with return code 0
