[2024-06-09 14:05:59,410] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.save_into_db 2024-06-05T02:00:00+00:00 [queued]>
[2024-06-09 14:05:59,501] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.save_into_db 2024-06-05T02:00:00+00:00 [queued]>
[2024-06-09 14:05:59,506] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-06-09 14:05:59,507] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-06-09 14:05:59,507] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-06-09 14:05:59,565] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): save_into_db> on 2024-06-05T02:00:00+00:00
[2024-06-09 14:05:59,599] {standard_task_runner.py:52} INFO - Started process 173 to run task
[2024-06-09 14:05:59,689] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'load_init_data', 'save_into_db', '2024-06-05T02:00:00+00:00', '--job-id', '56', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/load_init_data.py', '--cfg-path', '/tmp/tmpg9742c5e', '--error-file', '/tmp/tmp3_4x5vk4']
[2024-06-09 14:05:59,753] {standard_task_runner.py:77} INFO - Job 56: Subtask save_into_db
[2024-06-09 14:06:00,108] {logging_mixin.py:104} INFO - Running <TaskInstance: load_init_data.save_into_db 2024-06-05T02:00:00+00:00 [running]> on host dfb4a2808431
[2024-06-09 14:06:00,290] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_init_data
AIRFLOW_CTX_TASK_ID=save_into_db
AIRFLOW_CTX_EXECUTION_DATE=2024-06-05T02:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-05T02:00:00+00:00
[2024-06-09 14:06:00,775] {python.py:118} INFO - Done. Returned value was: None
[2024-06-09 14:06:00,807] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=load_init_data, task_id=save_into_db, execution_date=20240605T020000, start_date=20240609T140559, end_date=20240609T140600
[2024-06-09 14:06:00,867] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-09 14:06:00,904] {local_task_job.py:146} INFO - Task exited with return code 0
